# https://docs.tugboatqa.com/reference/tugboat-configuration/
# https://docs.tugboatqa.com/starter-configs/tutorials/drupal-10/
services:
  webserver:
    image: tugboatqa/php:8.3-apache
    default: true
    commands:
      init:
        - docker-php-ext-install opcache
        - a2enmod headers rewrite
        - echo "memory_limit = -1" >> /usr/local/etc/php/conf.d/my-php.ini
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"

        - sudo apt update
        - sudo apt install sqlite3

      build:
        - rm composer.lock || true
        - composer install
        - composer run drupal:install-dev

        # Make sure files and translations folders exist and are writable.
        - mkdir -p "${DOCROOT}/sites/default/files/translations"
        - chgrp -R www-data "${DOCROOT}/sites/default/files"
        - find "${DOCROOT}/sites/default/files" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \;

        # @todo For some reason the Drush "config:set" command run by composer
        #   run drupal:install-dev to enable verbose logging doesn't ultimately
        #   take effect. Manually change the settings until it can be debugged.
        - |
          echo "if (file_exists(__DIR__ . '/settings.local.php')) {
            include __DIR__ . '/settings.local.php';
          }" | sudo tee -a web/sites/default/settings.php
          sudo cp web/sites/example.settings.local.php \
            web/sites/default/settings.local.php

        # Set trusted_host_patterns configuration.
        - |
          echo "
          \$settings['trusted_host_patterns'] = [
            '^.*tugboatqa.com\$',
          ];" \
            | sudo tee -a web/sites/default/settings.local.php

        # Disable rebuild access.
        - |
          echo "
          \$settings['rebuild_access'] = FALSE;" \
            | sudo tee -a web/sites/default/settings.local.php

        # Make everything writable.
        - sudo chmod -R 777 "${DOCROOT}"

        # Run cron to populate the search index, etc.
        - php vendor/bin/drush core:cron

        # DEBUGGING:

        # Current commit.
        - echo; git show -s HEAD

        # PHP version.
        - echo; php -v | head -1

        # Drush status.
        - echo; php vendor/bin/drush core:status || true

        # Apache smoke tests.
        - echo; curl --silent http://localhost/ | grep "<title>" || true
        - echo; curl --location --silent http://localhost/node/1 | grep "<title>" || true
